version: "3"

services: 
    graphqplserver:
        restart: always
        build:  . 
        ports:
          - 4000:4000
        depends_on:
          - "postgresdatabase"
    postgresdatabase:
        image: "postgres" # use latest official postgres version
        env_file:
          - .env # configure postgres
        volumes:
          - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
    database-data: